# Auto-generated by brew/update-tap.sh.
# Hand-edits will be overwritten on the next release.
class Factorly < Formula
  desc "Postman for developers building AI agent toolchains"
  homepage "https://github.com/factorly-dev/factorly"
  version "0.18.0"
  license "GPL-3.0-or-later"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/factorly-dev/factorly/releases/download/v#{version}/factorly-#{version}-darwin-arm64"
      sha256 "7f6ef78b71e23f1252b041eb96a4fb12711e53b86020b718ac50a054c109b3d1"
    end
    on_intel do
      url "https://github.com/factorly-dev/factorly/releases/download/v#{version}/factorly-#{version}-darwin-amd64"
      sha256 "4667022e48d73cf437f3d376418b6a18ec4d3c1ae3192759edb29276761763d8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/factorly-dev/factorly/releases/download/v#{version}/factorly-#{version}-linux-arm64"
      sha256 "14c1943662fc36149bce072c46d2dc0f2ba6dd3c422a4663a816f70a7edcd812"
    end
    on_intel do
      url "https://github.com/factorly-dev/factorly/releases/download/v#{version}/factorly-#{version}-linux-amd64"
      sha256 "4304ca1c82dffcdd398ab13043df9afd5c9c0abdbc4458f7ef30c4e8e439c559"
    end
  end

  def install
    binary = Dir["factorly-*"].first
    bin.install binary => "factorly"
  end

  test do
    output = shell_output("#{bin}/factorly version")
    assert_match "factorly", output
    assert_match version.to_s, output
  end
end
