# Auto-generated by brew/update-tap.sh.
# Hand-edits will be overwritten on the next release.
class Factorly < Formula
  desc "Postman for developers building AI agent toolchains"
  homepage "https://github.com/factorly-dev/factorly"
  version "0.17.4"
  license "GPL-3.0-or-later"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/factorly-dev/factorly/releases/download/v#{version}/factorly-#{version}-darwin-arm64"
      sha256 "960b1ab3a54bdeaf8783f7cde7eca623a348429550312a7634996ec349999ba6"
    end
    on_intel do
      url "https://github.com/factorly-dev/factorly/releases/download/v#{version}/factorly-#{version}-darwin-amd64"
      sha256 "9f1ed501f1fc770744c66831730d96c187b2d769c8e2c1c906b75b7ce55c721a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/factorly-dev/factorly/releases/download/v#{version}/factorly-#{version}-linux-arm64"
      sha256 "a851b29b8571c15e52b4b641913135fff2b5beef4ad29f6d5a569f7b54c12a4d"
    end
    on_intel do
      url "https://github.com/factorly-dev/factorly/releases/download/v#{version}/factorly-#{version}-linux-amd64"
      sha256 "ae4c8511c080a8c7d334fc2c0c9459274e708f528ebaf1bae744886cc09a1270"
    end
  end

  def install
    binary = Dir["factorly-*"].first
    bin.install binary => "factorly"
  end

  test do
    output = shell_output("#{bin}/factorly version")
    assert_match "factorly", output
    assert_match version.to_s, output
  end
end
