# Auto-generated by brew/update-tap.sh.
# Hand-edits will be overwritten on the next release.
class Factorly < Formula
  desc "Postman for developers building AI agent toolchains"
  homepage "https://github.com/factorly-dev/factorly"
  version "0.17.2"
  license "GPL-3.0-or-later"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/factorly-dev/factorly/releases/download/v#{version}/factorly-#{version}-darwin-arm64"
      sha256 "154185b3bb17cce5026be342cbe23641cdaa303f681479e454c2837a76dcde64"
    end
    on_intel do
      url "https://github.com/factorly-dev/factorly/releases/download/v#{version}/factorly-#{version}-darwin-amd64"
      sha256 "9762d832feb2d57e85c45786374b736e6fbda051d6cbafbab2d5c4a8f0ed9099"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/factorly-dev/factorly/releases/download/v#{version}/factorly-#{version}-linux-arm64"
      sha256 "6e915969bda00bf606dd95b1776c7783f40bd49b13f7aa3010b0b9c0862e3631"
    end
    on_intel do
      url "https://github.com/factorly-dev/factorly/releases/download/v#{version}/factorly-#{version}-linux-amd64"
      sha256 "0c1a8bc5e2f4ef19d8bc02fb5578bf8698e2b92353ad810ea6d004e6ab049afe"
    end
  end

  def install
    binary = Dir["factorly-*"].first
    bin.install binary => "factorly"
  end

  test do
    output = shell_output("#{bin}/factorly version")
    assert_match "factorly", output
    assert_match version.to_s, output
  end
end
